### ISSUE TITLE
Require issue

### ISSUE THREAD

**Issue by olimorris** [kigster/colored2#2] opened 2017-01-28 16:39 UTC
I'm getting a weird `require` issue with this:

```
setup.rb:5:in `require': cannot load such file -- colored2 (LoadError)
        from setup.rb:5:in `<top (required)>'
        from Installer.rb:259:in `load'
        from Installer.rb:259:in `<main>'
```

It's in my gem list and my bundle list. Any issues on your end?

**Comment by kigster** [comment] 2017-01-28 18:48
I'll check in a few.

**Comment by kigster** [comment] 2017-01-28 18:50
Are you running `bin/setup`?

If not, how exactly do you get to this error?

**Comment by olimorris** [comment] 2017-01-28 19:01
I'm running a simple file which begins to setup the installation of my dotfiles. the `setup.rb` file requires some modules and it's in the first line I get the error:

```
#!/usr/bin/ruby -w

# Require Gems
require 'bundler/setup'
require 'colored2'
```

When I use the old `colored` repo in my Gemfile, it works just fine.

**Comment by kigster** [comment] 2017-01-28 20:11
OK that should be fixed, please `gem uninstall colored2; gem install colored2`.

**Comment by farwayer** [comment] 2017-02-03 03:50
@kigster Just trapped into this issue

```bash
$ gem list | grep colored                                                                                              
colored (1.2)
colored2 (3.1.1)

$ irb                                                                                                                  
irb(main):001:0> require 'colored'
=> true
irb(main):002:0> require 'colored2'
LoadError: cannot load such file -- colored2
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
```

**Comment by kigster** [comment] 2017-02-05 02:34
This is really strange, I can not reproduce this. 

Here is an identical session on MRI ruby 2.4.0 and 2.3.3 that works without any problems (there is no difference between ruby versions, so I am only including one output):

```bash
❯ gem list | grep colored
colored (1.2)
colored2 (3.1.1)
```

```ruby
❯ irb
irb(main):001:0> require 'colored'
=> true
irb(main):002:0> require 'colored2'
=> true
irb(main):003:0>
```

May I suggest you do:

```bash
gem uninstall -a colored colored2
gem install colored colored2
ruby -e 'require "colored"; require "colored2"; puts "success"'
```

**Comment by farwayer** [comment] 2017-02-06 03:12
@kigster Fastlane also had the problem when trying to use colored2 (3.1.1) https://github.com/fastlane/fastlane/issues/8111

**Comment by rmg** [comment] 2017-02-09 02:14
I've seen this problem and tracked it down to globally installing as `root` and then `ruby`/`irb` running as non-root. The problem is the published gem has incorrect permissions set on the files themselves.

From the `data.tar.tgz` embedded in the v2.0.2 release:
```
$ tar -tvf data.tar.gz
-rw-r-----  0 wheel  wheel    1113  9 Mar  2016 LICENSE
-rw-r-----  0 wheel  wheel    1789  9 Mar  2016 README.md
-rw-r-----  0 wheel  wheel     227  9 Mar  2016 Rakefile
-rw-r-----  0 wheel  wheel    2309  9 Mar  2016 lib/colored2.rb
-rw-r--r--  0 wheel  wheel    2547  9 Mar  2016 lib/colored2/ascii_decorator.rb
-rw-r--r--  0 wheel  wheel     405  9 Mar  2016 lib/colored2/constants.rb
-rw-r--r--  0 wheel  wheel      70  9 Mar  2016 lib/colored2/numbers.rb
-rw-r--r--  0 wheel  wheel      45  9 Mar  2016 lib/colored2/object.rb
-rw-r--r--  0 wheel  wheel      45  9 Mar  2016 lib/colored2/strings.rb
-rw-r--r--  0 wheel  wheel      40  9 Mar  2016 lib/colored2/version.rb
-rw-r--r--  0 wheel  wheel     491  9 Mar  2016 spec/colored2_numbers_spec.rb
-rw-r--r--  0 wheel  wheel     567  9 Mar  2016 spec/colored2_object_spec.rb
-rw-r--r--  0 wheel  wheel     462  9 Mar  2016 spec/colored2_spec.rb
-rw-r-----  0 wheel  wheel    2607  9 Mar  2016 spec/colored2_string_spec.rb
-rw-r--r--  0 wheel  wheel      91  9 Mar  2016 spec/spec_helper.rb
```

And from the most recent, v3.0.1:
```
$ tar -tvf data.tar.gz
-rw-r-----  0 wheel  wheel    1113 28 Jan 12:09 LICENSE
-rw-r-----  0 wheel  wheel    3754 28 Jan 12:09 README.md
-rw-r-----  0 wheel  wheel     227 28 Jan 12:09 Rakefile
-rw-r-----  0 wheel  wheel    2536 28 Jan 12:09 lib/colored2.rb
-rw-r-----  0 wheel  wheel    2136 28 Jan 12:09 lib/colored2/ascii_decorator.rb
-rw-r-----  0 wheel  wheel    1057 28 Jan 12:09 lib/colored2/codes.rb
-rw-r-----  0 wheel  wheel     323 28 Jan 12:09 lib/colored2/numbers.rb
-rw-r-----  0 wheel  wheel     106 28 Jan 12:09 lib/colored2/object.rb
-rw-r-----  0 wheel  wheel     106 28 Jan 12:09 lib/colored2/strings.rb
-rw-r-----  0 wheel  wheel      40 28 Jan 12:09 lib/colored2/version.rb
-rw-r-----  0 wheel  wheel     702 28 Jan 12:09 spec/colored2/numbers_spec.rb
-rw-r-----  0 wheel  wheel     565 28 Jan 12:09 spec/colored2/object_spec.rb
-rw-r-----  0 wheel  wheel    2617 28 Jan 12:09 spec/colored2/strings_spec.rb
-rw-r-----  0 wheel  wheel     462 28 Jan 12:09 spec/colored2_spec.rb
-rw-r-----  0 wheel  wheel      59 28 Jan 12:09 spec/spec_helper.rb
```

Note that the files are all `0640`, which is preserved at install time.

@kigster you should be able to fix this by running `chmod -R o+r ./` on your checkout and cutting a new release.

**Comment by kigster** [comment] 2017-02-10 01:07
@rmg OMG thank you so much for helping figure this out!  It's been years since I used system ruby, so of course I wouldn't bump into this problem locally, as I use rbenv.

I am going to add a rake task to ensure permissions are correct for all files before releasing the gem in the future.

Once again — your help figuring this out is very much appreciated.

**Comment by kigster** [comment] 2017-02-14 22:43
Please update to 3.1.2 as it should resolve the issues.

**Closed as completed by kigster** 2017-02-14 22:43 UTC

**Comment by arkirchner** [comment] 2024-09-02 07:39
@kigster 
The same issue was reintroduced in version 4. Loading the gem as none root user does not work.

```
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- /usr/local/bundle/ruby/3.3.0/gems/colored2-4.0.0/lib/colored2.rb (LoadError)
```

Version 4
```
rails@724e4edd24da:/rails$ ls -al /usr/local/bundle/ruby/3.3.0/gems/colored2-4.0.0/lib/
total 16
drwxr-xr-x 3 root root 4096 Sep  2 04:02 .
drwxr-xr-x 3 root root 4096 Sep  2 04:02 ..
drwxr-xr-x 2 root root 4096 Sep  2 04:02 colored2
-rw-r----- 1 root root 2482 Sep  2 04:02 colored2.rb
```

Version 3.1.2
```
rails@bb5ce8a817f7:/rails$ ls -al /usr/local/bundle/ruby/3.3.0/gems/colored2-3.1.2/lib/
total 16
drwxr-xr-x 3 root root 4096 Sep  2 07:18 .
drwxr-xr-x 4 root root 4096 Sep  2 07:18 ..
drwxr-xr-x 2 root root 4096 Sep  2 07:18 colored2
-rw-r--r-- 1 root root 2536 Sep  2 07:18 colored2.rb
```

I was able to fix it by downgrading it.

**Comment by ChrLau** [comment] 2025-01-09 13:07
> I am going to add a rake task to ensure permissions are correct for all files before releasing the gem in the future.

Can we please have that rake task? 😄

**Comment by kigster** [comment] 2025-01-09 18:19
I'll fix this today. Sorry didn't see the issue reopened.

**Comment by ChrLau** [comment] 2025-01-10 11:36
No worries! Luckily there is an easy workaround. I am more curious as to why no one reported that sooner. 😆
